GET http://localhost:3000/organizations

###

POST http://localhost:3000/organizations
Content-Type: application/json

{
    "name": "Test Corp.",
    "started": "1970-01-01T05:00:00.000Z",
    "public": true,
    "employees": 324
}
